import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import starlightClientMermaid from '@pasqal-io/starlight-client-mermaid';

export default defineConfig({
  site: 'https://shusha-group.github.io',
  base: '/gsd2-guide',
  integrations: [
    starlight({
      title: 'GSD 2',
      plugins: [starlightClientMermaid()],
      customCss: [
        './src/styles/custom.css',
        './src/styles/terminal.css',
      ],
      components: {
        Header: './src/components/Header.astro',
        Footer: './src/components/Footer.astro',
      },
      sidebar: [
        { label: 'Home', link: '/' },
        { label: 'Changelog', link: '/changelog/' },
        {
          label: 'User Guide',
          items: [
            { label: 'Getting Started', link: '/getting-started/' },
            { label: 'Developing with GSD', link: '/user-guide/developing-with-gsd/' },
            { label: 'Discussing a Milestone', link: '/user-guide/discussing-a-milestone/' },
          ],
        },
        {
          label: 'Commands',
          items: [
            { label: 'Commands Reference', link: '/commands/' },
            { label: '/gsd auto', link: '/commands/auto/' },
            { label: '/gsd stop', link: '/commands/stop/' },
            { label: '/gsd', link: '/commands/gsd/' },
            { label: '/gsd next', link: '/commands/next/' },
            { label: '/gsd quick', link: '/commands/quick/' },
            { label: '/gsd discuss', link: '/commands/discuss/' },
            { label: '/gsd status', link: '/commands/status/' },
            { label: '/gsd visualize', link: '/commands/visualize/' },
            { label: '/gsd queue', link: '/commands/queue/' },
            { label: '/gsd steer', link: '/commands/steer/' },
            { label: '/gsd capture', link: '/commands/capture/' },
            { label: '/gsd triage', link: '/commands/triage/' },
            { label: '/gsd knowledge', link: '/commands/knowledge/' },
            { label: '/gsd cleanup', link: '/commands/cleanup/' },
            { label: '/gsd doctor', link: '/commands/doctor/' },
            { label: '/gsd forensics', link: '/commands/forensics/' },
            { label: '/gsd prefs', link: '/commands/prefs/' },
            { label: '/gsd mode', link: '/commands/mode/' },
            { label: '/gsd skill-health', link: '/commands/skill-health/' },
            { label: '/gsd hooks', link: '/commands/hooks/' },
            { label: '/gsd run-hook', link: '/commands/run-hook/' },
            { label: '/gsd migrate', link: '/commands/migrate/' },
            { label: '/gsd export', link: '/commands/export/' },
            { label: 'gsd config', link: '/commands/config/' },
            { label: 'gsd update', link: '/commands/update/' },
            { label: '/gsd keys', link: '/commands/keys/' },
            { label: '/gsd logs', link: '/commands/logs/' },
            { label: '/gsd new-milestone', link: '/commands/new-milestone/' },
            { label: '/gsd skip', link: '/commands/skip/' },
            { label: '/gsd undo', link: '/commands/undo/' },
            { label: 'Keyboard Shortcuts', link: '/commands/keyboard-shortcuts/' },
            { label: 'CLI Flags', link: '/commands/cli-flags/' },
            { label: 'Headless Mode', link: '/commands/headless/' },
          ],
        },
        {
          label: 'Recipes',
          items: [
            { label: 'Fix a Bug', link: '/recipes/fix-a-bug/' },
            { label: 'Small Change', link: '/recipes/small-change/' },
            { label: 'New Milestone', link: '/recipes/new-milestone/' },
            { label: 'Handle UAT Failures', link: '/recipes/uat-failures/' },
            { label: 'Error Recovery', link: '/recipes/error-recovery/' },
            { label: 'Working in Teams', link: '/recipes/working-in-teams/' },
            { label: 'Auto Mode', link: '/auto-mode/' },
            { label: 'Git Strategy', link: '/git-strategy/' },
            { label: 'Working in Teams', link: '/working-in-teams/' },
            { label: 'Cost Management', link: '/cost-management/' },
            { label: 'Token Optimization', link: '/token-optimization/' },
            { label: 'Dynamic Model Routing', link: '/dynamic-model-routing/' },
            { label: 'Captures & Triage', link: '/captures-triage/' },
            { label: 'Parallel Orchestration', link: '/parallel-orchestration/' },
          ],
        },
        {
          label: 'Reference',
          items: [
            { label: 'Overview', link: '/reference/' },
            { label: 'Commands', link: '/reference/commands/' },
            { label: 'Skills', link: '/reference/skills/' },
            { label: 'Extensions', link: '/reference/extensions/' },
            { label: 'Agents', link: '/reference/agents/' },
            { label: 'Shortcuts', link: '/reference/shortcuts/' },
          ],
        },
        {
          label: 'Guides',
          items: [
            { label: 'Configuration', link: '/configuration/' },
            { label: 'Architecture', link: '/architecture/' },
            { label: 'Skills', link: '/skills/' },
            { label: 'Workflow Visualizer', link: '/visualizer/' },
            { label: 'Remote Questions', link: '/remote-questions/' },
            { label: 'Migration from v1', link: '/migration/' },
            { label: 'Troubleshooting', link: '/troubleshooting/' },
          ],
        },
      ],
    }),
  ],
});
